
" Plugins...
call plug#begin('~/.vim/plugged')
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'mhinz/vim-signify'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'farmergreg/vim-lastplace'
Plug 'tyrannicaltoucan/vim-quantum'
Plug 'tpope/vim-surround'
Plug 'terryma/vim-multiple-cursors'
Plug 'kien/ctrlp.vim'
call plug#end()

"I do not use vi. I can turn off this config
set nocompatible

syntax enable
set number
set hlsearch
set smartindent
set nowrap
set tabstop=8
set shiftwidth=8
set noexpandtab
set clipboard+=unnamed
set nocscopeverbose
"indent"
filetype indent on
filetype plugin on
set omnifunc=syntaxcomplete#Complete
"allow vim to search in directories
set path+=**
"display all matching file when we tab complete
set wildmenu
set spell
" disable Ex mode
noremap Q <NOP>

"colorscheme
set background=dark
colorscheme hybrid_material

let mapleader=","
let maplocalleader="\\"

function! GetRunningOS()
	if system('uname -v')=~ 'Ubuntu'
		return 'ubuntu'
	endif
	if system('uname -v')=~ 'Darwin'
		return 'macos'
	endif
	return 'fedora'
endfunction

if &term != "xterm"
	let &colorcolumn="80,".join(range(120,999),",")
endif

"highlighting line number"
set cursorline

"Move the current line down
map - dd _p
"Edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
""Load vimrc
nnoremap <leader>sv :source $MYVIMRC<cr>
"Surrond the current word with double quotes
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
"Close current tab
nnoremap tc :tabclose<cr>
"New tab
nnoremap tn :tabnew<cr>
"Go to next tab
nnoremap tj  :tabnext<CR>
"Go to previous tab
nnoremap tk  :tabprev<CR>
""Go to normal mode from insert mode
inoremap jk <esc>
"Disable esc key
inoremap <esc> <nop>
""Disable arrows keys! Use vim correctly
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
"folding
let javaScript_fold=1
let sh_fold_enabled=1
let c_fold_enabled=1

augroup filetype_html
	autocmd!
	autocmd FileType html nnoremap <buffer> <localleader>f Vatzf
augroup END

"Abbreviations
iabbrev ssig -- <cr>José Guilherme Vanz<cr>guilherme.sft@gmail.com

au BufRead COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])

" Remove all trailing whitespace when saving
" See http://vim.wikia.com/wiki/Remove_unwanted_spaces
autocmd BufWritePre * :%s/\s\+$//e

" toggle invisible characters
set invlist
set listchars=tab:▸\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
highlight SpecialKey ctermbg=none
set showbreak=↪
nmap <leader>l :set list!<cr>

" plugins
"ctrlp plugin config
let g:ctrlp_working_path_mode = 'ra'

"vim-multiples-cursors
let g:multi_cursor_prev_key='<C-b>'
let g:multi_cursor_next_key='<C-m>'

"vim-signify
let g:signify_vcs_list = [ 'git', 'hg', 'svn' ]

"Toggle NERDTree plugin
nmap <leader>n :NERDTreeToggle<CR>
"NERDTree ignore file types
let NERDTreeIgnore = ['\.pyc$']

" vim airline
let g:airline_theme='quantum'
let g:airline_powerline_fonts=1

